spring.datasource.url=jdbc:postgresql://localhost:5416/trackhub
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=TrackHubSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong
jwt.expiration=3600000