spring.datasource.url=jdbc:postgresql://localhost:5416/trackhub
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JWT Configuration
jwt.secret=TrackHubSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong
jwt.expiration=3600000